/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Beans.Esqueleto;
import Beans.Sistema;
import DAOs.BancoConnection;
import DAOs.EsqueletoDAO;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author plocabral
 */

public class Menu extends javax.swing.JFrame {

    ArrayList<Esqueleto> gerado = new ArrayList<>();
    ArrayList<String> files = new ArrayList<>();
    DefaultListModel model = new DefaultListModel();
    JFileChooser arquivo = new JFileChooser();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        ImageIcon Icon = (new ImageIcon(Menu.class.getResource("/Resources/database.png")));
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setLocationRelativeTo(null);
        listt.setSelectedIndex(-1);
        this.setTitle("Conversor TXT/SQLQuerys");
        this.setIconImage(Icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        GerarBtn = new javax.swing.JButton();
        SelecionarBtn = new javax.swing.JButton();
        TesteConexaoBtn = new javax.swing.JButton();
        teste = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listt = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        log = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GerarBtn.setText("Gerar");
        GerarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarBtnActionPerformed(evt);
            }
        });

        SelecionarBtn.setText("Selecionar Arquivo:");
        SelecionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarBtnActionPerformed(evt);
            }
        });

        TesteConexaoBtn.setText("Testar Conexão Banco");
        TesteConexaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteConexaoBtnActionPerformed(evt);
            }
        });

        teste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        teste.setForeground(new java.awt.Color(0, 51, 51));
        teste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TXT TO BD");

        listt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listtValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listt);

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        log.setText("Ver LOG");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelecionarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TesteConexaoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GerarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelecionarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TesteConexaoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teste, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GerarBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(log)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelecionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarBtnActionPerformed
        int igual = 0;

        FileNameExtensionFilter filtroTXT = new FileNameExtensionFilter("Arquivos TXT", "txt");
        arquivo.addChoosableFileFilter(filtroTXT);
        arquivo.setMultiSelectionEnabled(true);
        arquivo.setAcceptAllFileFilterUsed(false);

        if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            for (File selectedFile : arquivo.getSelectedFiles()) {
                if (listt.getModel().getSize() != 0) {
                    for (int i = 0; i < listt.getModel().getSize(); i++) {
                        Object item = listt.getModel().getElementAt(i);
                        if (selectedFile.getPath().equalsIgnoreCase(item.toString())) {
                            igual = 1;
                        }
                    }
                    if (igual != 1) {
                        model.addElement(selectedFile);
                    } else {
                        JOptionPane.showMessageDialog(this, "ERROR: ARQUIVO SELECIONADO JÁ EXISTENTE!");
                    }
                } else {
                    model.addElement(selectedFile);
                }
            }
            listt.setModel(model);
        }
    }//GEN-LAST:event_SelecionarBtnActionPerformed

    private void GerarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarBtnActionPerformed

        for (int i = 0; i < listt.getModel().getSize(); i++) {

            FileWriter WR = null;
            try {
                WR = new FileWriter(Sistema.getInstance().getArquivo(), true);
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            BufferedWriter BW = new BufferedWriter(WR);
            Object item = listt.getModel().getElementAt(i);

            Calendar cal = new GregorianCalendar();

            try {
                BW.newLine();
                BW.write(("\t Data/Hora: " + cal.getTime().toString()));
                BW.write("\tArquivo: " + item);
                BW.newLine();
                BW.newLine();
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }

            ArrayList<String> a = null;

            File f = new File(item.toString());

            if (f.exists() && !f.isDirectory()) {
                a = this.retornoArray(f);
            }

            if (a.size() != 0) {

                for (int s = 4; s < a.size(); s++) {
                    String[] arrayobj = a.get(s).split(" ");
                    try {
                        Esqueleto esq = new Esqueleto(Integer.parseInt(arrayobj[0]), arrayobj[1], arrayobj[2], Float.parseFloat(arrayobj[3]),
                                Float.parseFloat(arrayobj[4]));
                        gerado.add(esq);
                    } catch (NumberFormatException e) {
                        try {
                            BW.write(e.toString());
                        } catch (IOException ex) {
                            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

                try {
                    BW.newLine();
                    BW.write("Querys lançadas: " + gerado.size() + "");
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    EsqueletoDAO esqdao = null;

                    try {
                        esqdao = new EsqueletoDAO();
                    } catch (Exception ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        ArrayList<String> aa = esqdao.add_cliente(gerado);
                        BW.newLine();
                        for (String string : aa) {

                            BW.write(string);
                            BW.newLine();
                        }
                        BW.newLine();
                        BW.write("\n\t\t-------------------------------------------------------------------\n");
                        BW.newLine();
                    } catch (IOException ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    gerado.clear();
                    BW.close();
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    WR.close();
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                System.out.println("Arquivo Vazio");
            }
        }

        limpar();
    }//GEN-LAST:event_GerarBtnActionPerformed

    private void TesteConexaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteConexaoBtnActionPerformed
        Connection con = null;
        try {
            con = BancoConnection.getConnection();
            teste.setText("OK");
        } catch (Exception ex) {
            teste.setText("FAIL");
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        BancoConnection.closeConnection(con);
    }//GEN-LAST:event_TesteConexaoBtnActionPerformed

    private void listtValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listtValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listtValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        mostrarlog();
    }//GEN-LAST:event_logActionPerformed

    public void mostrarlog() {
        try {
            Desktop.getDesktop().browse(Sistema.getInstance().getArquivo().toURI());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void limpar() {
        model.clear();
        listt.setModel(model);
    }

    public ArrayList<String> retornoArray(File file) {

        ArrayList<String> linhas = new ArrayList<>();
        //Criamos um scanner, para ler do arquivo.
        Scanner input = null;
        try {
            input = new Scanner(file);
            //Enquanto o arquivo tiver linhas
            while (input.hasNextLine()) {
                //Lemos a linha
                linhas.add(input.nextLine());
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } finally {
            //Fechamos o arquivo
            if (input != null) {
                input.close();
            }
        }
        //Retornamos o texto lido.
        return linhas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GerarBtn;
    private javax.swing.JButton SelecionarBtn;
    private javax.swing.JButton TesteConexaoBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listt;
    private javax.swing.JButton log;
    private javax.swing.JLabel teste;
    // End of variables declaration//GEN-END:variables
}
